## Numpy array and basics
learn about numpy

In [2]:
import numpy as np


## Creating array from list


In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)

1D array:  [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [8]:
py_list = [1,2,3]
print("list multiplication by 2:",py_list * 2)

py_array = np.array([1,2,3])#element wise multiplication
print("array multiplication by 2:",py_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation Time: ", time.time()-start)

start = time.time()
py_array = np.arange(100000) * 2
print(py_array)
print("\n array operation Time: ", time.time()-start)


list multiplication by 2: [1, 2, 3, 1, 2, 3]
array multiplication by 2: [2 4 6]

 List operation Time:  0.16216182708740234
[     0      2      4 ... 199994 199996 199998]

 array operation Time:  0.0014302730560302734


### Creating array from scratch


In [32]:
zero = np.zeros((2,3))
print("zeroes array: ")
print(zero)
print()

one = np.ones((2,4))
print("ones array: ")
print(one)
print()

full = np.full((2,2),4)
print("fulls array:")
print(full)
print()

random = np.random.random((2,4)) * 10
random = random - random%1 #skipping decimal part
print(random)

zeroes array: 
[[0. 0. 0.]
 [0. 0. 0.]]

ones array: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

fulls array:
[[4 4]
 [4 4]]

[[2. 5. 5. 5.]
 [8. 5. 0. 0.]]


### Vector, Matrix and Tensor

In [34]:
vector = np.array([1,2,3])
print("vector:")
print(vector)
print()

matrix = np.array([[2,3],
                   [3,4]])
print("Matrix:\n",matrix)

print()

tensor = np.array([[1,2],[2,3],
                   [4,5],[5,6]])
print("tensors:\n",tensor)

vector:
[1 2 3]

Matrix:
 [[2 3]
 [3 4]]

tensors:
 [[1 2]
 [2 3]
 [4 5]
 [5 6]]


### Array Properties

In [3]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("DType: ",arr.dtype)




Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


### Array Reshaping

In [ ]:
original = np.arange(12)
print("original array: \n",original)

reshaped = original.reshape((3,4))
print("reshaped array: \n",reshaped)

flattened = reshaped.flatten()
print("flattend : \n", flattened)

raveled = reshaped.ravel()#returns view instead of copy
print("raveled: \n",raveled)

#transpose
transpose = reshaped.T
print("transposed: \n",transpose)

original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transposed: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
