## Numpy Array Operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing",arr[2:7])
print("step: ",arr[2:7:2])
print("negative indexing: ",arr[-3:-1])


basic slicing [3 4 5 6 7]
step:  [3 5 7]
negative indexing:  [7 8]


In [4]:
arr_2d =  np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print("specific element: ",arr_2d[1,2])#[row,column]  only on Numpy
print("Entire row: ",arr_2d[1])
print("Entire column: ",arr_2d[:,2])
print(arr_2d[1][2])

specific element:  6
Entire row:  [4 5 6]
Entire column:  [3 6 9]
6


### Sorting


In [22]:
unsorted = np.array([4,5,2,1,7,6])
print("Sorted array: ",np.sort(unsorted))

arr_2d = np.array([[1,5,2],
                   [4,3,1],
                   [3,6,4]])
print("2D array sort by column:\n",np.sort(arr_2d,axis=0))
print("2D array sort by row:\n",np.sort(arr_2d,axis=1))


Sorted array:  [1 2 4 5 6 7]
2D array sort by column:
 [[1 3 1]
 [3 5 2]
 [4 6 4]]
2D array sort by row:
 [[1 2 5]
 [1 3 4]
 [3 4 6]]


### Filter

In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
even = arr[arr % 2 == 0]#in numpy this expressions are evaluate first
print("Filtered array: ",even)

Filtered array:  [ 2  4  6  8 10]


## FIlter with mask

In [25]:
mask = arr > 5
print("numbers greater than 5: ", arr[mask])

numbers greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()


In [27]:
indices = [0,2,4]
print(arr[indices])

where_result = np.where(arr > 5)
print(where_result)#indexes of true where condition
print("where: ", arr[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
where:  [ 6  7  8  9 10]


In [30]:
condition_array = np.where(arr>5, True , False)
print("Condition array: ",condition_array)
print("arr for satisfied condition: ",arr[condition_array])

Condition array:  [False False False False False  True  True  True  True  True]
arr for satisfied condition:  [ 6  7  8  9 10]


## Adding and removing data

In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print("combined array: ", combined)

combined array:  [1 2 3 4 5 6]


###  array compatability


In [33]:
a = np.array([1,2,3])
b= np.array([4,5,6])
c= np.array([7,9,0])
print("Is arrays compatible: ", a.shape == b.shape)

Is arrays compatible:  True


In [38]:
original = np.array([[1,2],[3,4]])
new_row = np.array([7,8])
with_new_row = np.vstack((original,new_row))#add new row- vertical stack
print("original:\n",original)
print("with row:\n",with_new_row)

new_col = np.array([[9],[8]])
with_new_col = np.hstack((original, new_col))#horizontal stack(columnwise adding elements)
print("with new col:\n",with_new_col)


original:
 [[1 2]
 [3 4]]
with row:
 [[1 2]
 [3 4]
 [7 8]]
with new col:
 [[1 2 9]
 [3 4 8]]


In [ ]:
arr = np.array([1,2,3,4,5,6])
delete = np.delete(arr,2)
print("array after delete: ",delete)# here the new array after modification is returned, instead of the deleted element

array after delete:  [1 2 4 5 6]
